### ISSUE TITLE
Questions regarding TCGA-ESCA typing

### ISSUE THREAD

**Issue by eting83646** [HKU-MedAI/WSI-HGNN#2]
Hi, may I ask how you got the 213 samples for the cancer typing task? Below is a screenshot of what I got when I access the TCGA-ESCA from the GDC portal. After filtering out the slides that are labeled normal, I only got 172 slides to work with. Could you provide the details of how you deal with slides that are labeled normal? Thanks in advance. 
![Screenshot 2023-06-12 224643](https://github.com/HKU-MedAI/WSI-HGNN/assets/48427534/59bddc8e-9d13-413b-8881-07b05a2ee9ba)

**Comment by howardchanth** [comment]
Hi there. For normal slides we processed them also and used them for cancer classification tasks (we performed cancer classification for BRCA and COAD instead). If I remember correctly, I think here you got 172 cases where in each case there could be multiple WSI images (see the last column of your screenshot). For the typing labels, you may obtain them from the clinical data (which can be obtained from official site). File name like nationwidechildrens.org_clinical_patient_esca.txt.

**Comment by eting83646** [comment]
Thank you for your prompt reply, but I still have some questions remaining. 
1.  From the portal, I got 156 cases of diagonistic slide and 172 cases of tissue slide which contains 158 and 238 WSIs respectively. May I know which level of slides are used for the typing task?
2. Indeed, of those 172 cases, 238 WSIs were provided; however, 66  of them were labeled Slide tissue Normal, not 213 WSIs to work with the typing task. 
3. After looking at the txt files provided, only 185 typing labels were given, I couldn't find one with 213 labels, could you kindly provide the manifest file for the WSIs and the txt file?

Thanks in advance.

**Comment by howardchanth** [comment]
For all benchmarking datasets and tasks, we use the magnification level of 20 and tissue slides to extract the patches (as diagnostic slides contain annotation labels).

For the ESCA typing labels, we have uploaded our label files under ./data/. It serves as the input of our pipeline for ESCA typing task.
