### ISSUE TITLE
May I know how could I get the label files about BRCA?

### ISSUE THREAD

**Issue by chenxinli001** [HKU-MedAI/WSI-HGNN#5]
May I know where could i find these two files in the project page of BRCA? i am a beginner for this project.... Or Would you mind directly share/upload these two files?

![image](https://github.com/HKU-MedAI/WSI-HGNN/assets/58136000/dea2bae0-c51e-4a94-9b01-5ce0228d2cd4)

I couldn't find the desired two files from the following two pages.. Thanks!
![image](https://github.com/HKU-MedAI/WSI-HGNN/assets/58136000/9ca55624-94e6-471a-affc-32e4aa4f7564)
![image](https://github.com/HKU-MedAI/WSI-HGNN/assets/58136000/dcbed038-8e02-4592-b5c9-95361ba08ad9)

**Comment by howardchanth** [comment]
I have uploaded the typing label file. For the set of WSIs with normal labels, you may check the following file from the TCGA biomedical data, there should be a column called Slide Tissue Normal. Then you just group the names of all the normal WSIs into the normal list txt file.

nationwidechildrens.org_biospecimen_sample_BRCA.txt
