### ISSUE TITLE
Missing instruction for accessing the pre-trained weights of hovernet

### ISSUE THREAD

**Issue by chenxinli001** [HKU-MedAI/WSI-HGNN#6]

**Comment by chenxinli001** [comment]
I found the repo of hovernet. Thx

**Comment by hmylzd** [comment]
> I found the repo of hovernet. Thx

Hello, can you please tell us where you found it?

**Comment by hmylzd** [comment]
> I found the repo of hovernet. Thx

Hello, can you please tell me where you found it？Thank you very much!

**Comment by chenxinli001** [comment]
> > I found the repo of hovernet. Thx
> 
> Hello, can you please tell me where you found it？Thank you very much!

[hovernet](https://github.com/vqdang/hover_net)

**Comment by hmylzd** [comment]
Thank you very much!




洛柒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HKU-MedAI/WSI-HGNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月29日(星期二) 下午3:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HKU-MedAI/WSI-HGNN] Missing instruction for accessing the pre-trained weights of hovernet (Issue #6)





   
I found the repo of hovernet. Thx
  
Hello, can you please tell me where you found it？Thank you very much!
  
hovernet
