### ISSUE TITLE
Annotations of the cancer staging task

### ISSUE THREAD

**Issue by innocence0206** [HKU-MedAI/WSI-HGNN#9]
Hi, thanks for your great work！
I'm interested in the cancer staging task, do you have detailed (pixel- or patch- level) annotations related to this task that can help verify the model‘s performance through comparing the attention map and ground truth? Looking forward to your reply.

**Comment by howardchanth** [comment]
Hi thank you for your interest and appreciation in our work. For TCGA datasets only slide-level labels are available (no matter cancer classification, staging or subtyping). We test our localization methods with Camelyon 16, you may check the original challenge page for the full data and labels.
